[panel,danger]
.Le démon refuse de démarrer...
--
Essayez de le démarrer en mode debug pour voir l'erreur.
--

[panel,danger]
.Lors du démarrage en mode debug j'ai : "socket already in use"...
--
Cela veut dire que le démon est démarré mais que Jeedom n'arrive pas à le stopper. Vous pouvez soit redémarrer tout le système, soit en ssh faire "killall -9 refxcmd.py".
--

[panel,danger]
.En mode debug j'ai l'erreur "timeout" qui apparaît...
--
Cette erreur arrive quand la clef ne répond pas dans les 10 secondes qui suivent une demande. Les causes connues peuvent être :

** incompatibilité de la clef GSM,
** problème avec la version du firmware de la clef.
--
